# Generated by Django 5.2 on 2025-04-30 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('claim', 'Исковое заявление'), ('motion', 'Ходатайство'), ('appeal', 'Апелляционная жалоба')], max_length=50)),
                ('description', models.TextField()),
                ('template_file', models.FileField(upload_to='templates/')),
                ('fields_schema', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.JSONField()),
                ('file', models.FileField(blank=True, null=True, upload_to='generated/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_key', models.CharField(max_length=40)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttemplate')),
            ],
        ),
    ]
