# Generated by Django 5.2 on 2025-05-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'verbose_name': 'Сгенерированный документ', 'verbose_name_plural': 'Сгенерированные документы'},
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='ai_enhancement',
            field=models.BooleanField(default=False, verbose_name='AI улучшение'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='ai_max_length',
            field=models.PositiveIntegerField(default=2000, verbose_name='Макс. длина AI'),
        ),
        migrations.AddField(
            model_name='documenttemplate',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активный'),
        ),
        migrations.AddField(
            model_name='generateddocument',
            name='document_content',
            field=models.TextField(blank=True, null=True, verbose_name='Содержимое документа'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='doc_type',
            field=models.CharField(choices=[('claim', 'Исковое заявление'), ('motion', 'Ходатайство'), ('appeal', 'Апелляционная жалоба')], max_length=50, verbose_name='Тип документа'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='fields_schema',
            field=models.JSONField(verbose_name='Схема полей'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название шаблона'),
        ),
        migrations.AlterField(
            model_name='documenttemplate',
            name='template_file',
            field=models.FileField(upload_to='templates/', verbose_name='Файл шаблона'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='content',
            field=models.JSONField(verbose_name='Данные документа'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='generated/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='session_key',
            field=models.CharField(max_length=40, verbose_name='Ключ сессии'),
        ),
        migrations.AlterField(
            model_name='generateddocument',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.documenttemplate', verbose_name='Шаблон'),
        ),
    ]
