# Generated by Django 5.2 on 2025-05-02 14:02

import json.decoder
import json.encoder
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documenttemplate_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttemplate',
            name='fields_schema',
            field=models.JSONField(decoder=json.decoder.JSONDecoder, default=dict, encoder=json.encoder.JSONEncoder, verbose_name='Схема полей'),
        ),
    ]
