# Generated by Django 5.2 on 2025-05-05 07:55

import django.db.models.deletion
import json.encoder
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_documenttemplate_fields_schema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documenttemplate',
            options={'ordering': ['name'], 'verbose_name': 'Шаблон документа', 'verbose_name_plural': 'Шаблоны документов'},
        ),
        migrations.AlterModelOptions(
            name='generateddocument',
            options={'ordering': ['-created_at'], 'verbose_name': 'Сгенерированный документ', 'verbose_name_plural': 'Сгенерированные документы'},
        ),
        migrations.CreateModel(
            name='AIRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('field_help', 'Помощь по полю'), ('generate', 'Генерация текста'), ('analysis', 'Анализ документа'), ('other', 'Другое')], max_length=20, verbose_name='Тип запроса')),
                ('request_data', models.JSONField(encoder=json.encoder.JSONEncoder, verbose_name='Данные запроса')),
                ('response_data', models.JSONField(encoder=json.encoder.JSONEncoder, verbose_name='Данные ответа')),
                ('is_error', models.BooleanField(default=False, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('processing_time', models.FloatField(null=True, verbose_name='Время обработки (сек)')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'История запроса AI',
                'verbose_name_plural': 'История запросов AI',
                'ordering': ['-created_at'],
            },
        ),
    ]
