# Generated by Django 5.2 on 2025-05-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_documenttemplate_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airequesthistory',
            name='api_endpoint',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='API Endpoint'),
        ),
        migrations.AddField(
            model_name='airequesthistory',
            name='model_used',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Использованная модель'),
        ),
    ]
