# Generated by Django 5.2 on 2025-05-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_airequesthistory_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='category',
            field=models.CharField(choices=[('civil', 'Гражданские дела'), ('arbitration', 'Арбитражные споры'), ('administrative', 'Административные дела'), ('criminal', 'Уголовные дела'), ('family', 'Семейные дела'), ('labor', 'Трудовые споры'), ('tax', 'Налоговые споры'), ('corporate', 'Корпоративные споры')], default='civil', max_length=50, verbose_name='Категория дела'),
        ),
    ]
