# Generated by Django 5.2 on 2025-05-11 23:07

import documents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_documenttemplate_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttemplate',
            name='dynamic_blocks',
            field=models.JSONField(default=list, help_text='JSON структура динамических блоков и их зависимостей', validators=[documents.models.validate_dynamic_blocks], verbose_name='Динамические блоки'),
        ),
    ]
